services:
  - type: web
    name: bloodsync-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DONATION_COOLDOWN_DAYS
        value: 90
